const videoManifest = {
  "Baby Shower": {
    "Videos": [
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-CANVAVIDEO-1.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-CANVAVIDEO-2.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-CANVAVIDEO-3.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-1.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-2.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-3.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-4.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-5.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-7.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-8.mp4",
      "./VIDEO-TEMPLATES/BABY-SHOWER/VIDEOS/BABY-PINVIDEO-9.mp4"
    ]
  },
  "Birthday": {
    "Videos": [
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-1.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-10.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-11.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-2.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-3.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-4.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-5.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-6.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-7.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-8.mp4",
      "./VIDEO-TEMPLATES/BIRTHDAY/VIDEOS/BIRTHDAY-CANVAVIDEO-9.mp4"
    ]
  },
  "Engagement": {
    "Videos": [
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-1.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-10.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-11.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-12.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-13.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-14.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-15.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-16.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-17.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-18.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-19.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-2.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-20.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-21.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-3.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-4.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-5.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-6.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-7.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-8.mp4",
      "./VIDEO-TEMPLATES/ENGAGEMENT/VIDEOS/ENG-CANVAVIDEO-9.mp4"
    ]
  },
  "House Warming": {
    "Videos": [
      "./VIDEO-TEMPLATES/HOUSE-WARMING/VIDEOS/HOUSE-CANVA-VIDEO-2.mp4",
      "./VIDEO-TEMPLATES/HOUSE-WARMING/VIDEOS/HOUSE-CANVAVIDEO-1.mp4",
      "./VIDEO-TEMPLATES/HOUSE-WARMING/VIDEOS/HOUSE-CANVAVIDEO-3.mp4"
    ]
  },
  "Naming Ceremony": {
    "Videos": [
      "./VIDEO-TEMPLATES/NAMING-CEREMONY/VIDEOS/NAME-CANVAVIDEO-1.mp4",
      "./VIDEO-TEMPLATES/NAMING-CEREMONY/VIDEOS/NAME-CANVAVIDEO-2.mp4",
      "./VIDEO-TEMPLATES/NAMING-CEREMONY/VIDEOS/NAME-CANVAVIDEO-3.mp4"
    ]
  },
  "Wedding": {
    "Videos": [
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-1.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-10.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-11.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-12.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-13.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-14.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-15.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-16.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-17.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-19.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-2.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-20.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-21.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-22.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-23.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-24.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-25.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-26.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-27.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-28.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-29.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-3.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-30.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-31.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-4.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-5.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-6.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-7.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-8.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WED-CANVA-VIDEO-9.mp4",
      "./VIDEO-TEMPLATES/WEDDING/VIDEOS/WEDDING-ADOBE-VIDEO1.mp4"
    ]
  }
};